"""initial_schema

Revision ID: fe1674cfc2e3
Revises: 
Create Date: 2026-06-22 17:07:16.996613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1674cfc2e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occasion_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('required_categories', sa.JSON(), nullable=True),
    sa.Column('optional_categories', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('occasion_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occasion_types_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('preferred_style', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=False),
    sa.Column('primary_color', sa.String(length=50), nullable=False),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=True),
    sa.Column('last_worn', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clothing_items_id'), ['id'], unique=False)

    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('color_score', sa.Float(), nullable=True),
    sa.Column('style_score', sa.Float(), nullable=True),
    sa.Column('occasion_score', sa.Float(), nullable=True),
    sa.Column('season_score', sa.Float(), nullable=True),
    sa.Column('repetition_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfits_id'), ['id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_occasions', sa.JSON(), nullable=True),
    sa.Column('preferred_styles', sa.JSON(), nullable=True),
    sa.Column('preferred_colors', sa.JSON(), nullable=True),
    sa.Column('avoid_colors', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_id'), ['id'], unique=False)

    op.create_table('wardrobe_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('category_breakdown', sa.JSON(), nullable=True),
    sa.Column('color_breakdown', sa.JSON(), nullable=True),
    sa.Column('most_worn_items', sa.JSON(), nullable=True),
    sa.Column('least_worn_items', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('wardrobe_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_statistics_id'), ['id'], unique=False)

    op.create_table('outfit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('worn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_history_id'), ['id'], unique=False)

    op.create_table('outfit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_items_id'), ['id'], unique=False)

    op.create_table('outfit_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recommended_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_recommendations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_recommendations_id'))

    op.drop_table('outfit_recommendations')
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_items_id'))

    op.drop_table('outfit_items')
    with op.batch_alter_table('outfit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_history_id'))

    op.drop_table('outfit_history')
    with op.batch_alter_table('wardrobe_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wardrobe_statistics_id'))

    op.drop_table('wardrobe_statistics')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_id'))

    op.drop_table('outfits')
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_items_id'))

    op.drop_table('clothing_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('occasion_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occasion_types_id'))

    op.drop_table('occasion_types')
    # ### end Alembic commands ###
